spring.datasource.url=jdbc:mysql://localhost:3306/banco_xyz?createDatabaseIfNotExists=true
spring.datasource.username=root
spring.datasource.password=NuevaClave123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.batch.job.enabled=true
spring.batch.jdbc.initialize-schema=always