spring.application.name=bff-web
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:8888}
server.port=8081

core.api.base-url=http://core-bancario

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9000/oauth2/jwks

server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bancoxyz

resilience4j.circuitbreaker.instances.core.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.core.sliding-window-size=4
resilience4j.circuitbreaker.instances.core.minimum-number-of-calls=4
resilience4j.circuitbreaker.instances.core.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.core.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.core.permitted-number-of-calls-in-half-open-state=2

management.endpoints.web.exposure.include=health,circuitbreakers,circuitbreakerevents
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true
