spring.application.name=servicio-clientes
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:8888}
server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/banco_clientes?createDatabaseIfNotExists=true
spring.datasource.username=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
