server.ssl.key-store-password={cipher}e9b95e266260c56f7b9b6cbaaf65fef5eb6ceedc88d077fef662886f5fabac25

# Token client_credentials de servicios-internos para llamar a otros servicios (seguridad-interna).
servicios-internos.token-uri=${AUTH_SERVER_URL:http://localhost:9000}/oauth2/token
servicios-internos.client-id=servicios-internos
servicios-internos.client-secret={cipher}a5d4426e535a3b13e295fcfc6b8d33d5b76216f99f7b21c5866658fe7cb399f251f5c46636ee4e328ddec41aa39712f515d40664d68bc8053b2188cbd08ad6f1
servicios-internos.scope=interno