spring.application.name=bff-cajero
spring.config.import=configserver:http://localhost:8888
server.port=8083

core.api.base-url=http://core-bancario

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

jwt.expiracion-ms=3600000

server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bancoxyz

resilience4j.circuitbreaker.instances.core.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.core.sliding-window-size=4
resilience4j.circuitbreaker.instances.core.minimum-number-of-calls=4
resilience4j.circuitbreaker.instances.core.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.core.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.core.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.core.ignore-exceptions=com.banco.bffcajero.exception.CoreErrorException

management.endpoints.web.exposure.include=health,circuitbreakers,circuitbreakerevents
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true
